apiVersion: apps/v1
kind: Deployment
metadata:
  name: mi-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      componente: web
  template:
    metadata:
      labels:
        componente: web
    spec:
      containers:
      - name: mi-pod
        image: httpd
        ports:
        - containerPort: 80
